name: ${rootProject.name}
version: '${version}'
main: ${main_class}
author: '${author}'
api-version: '${api_version}'
commands:
  box:
    description: "give gacha box"
    operator : admin
  toolbox:
    description: "give tool box"
    operator : admin